# Generated by Django 5.2 on 2025-05-04 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0003_usuario_pregunta_seguridad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
