# Generated by Django 5.2 on 2025-05-04 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0004_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensajesoporte',
            options={'ordering': ['creado_en'], 'verbose_name': 'Mensaje de Soporte', 'verbose_name_plural': 'Mensajes de Soporte'},
        ),
        migrations.AlterModelOptions(
            name='metodopago',
            options={'ordering': ['-es_predeterminado', '-creado_en'], 'verbose_name': 'Método de Pago', 'verbose_name_plural': 'Métodos de Pago'},
        ),
        migrations.AlterModelOptions(
            name='resena',
            options={'ordering': ['-fecha'], 'verbose_name': 'Reseña', 'verbose_name_plural': 'Reseñas'},
        ),
        migrations.AlterModelOptions(
            name='ticketsoporte',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Ticket de Soporte', 'verbose_name_plural': 'Tickets de Soporte'},
        ),
        migrations.RenameField(
            model_name='mensajesoporte',
            old_name='fecha_envio',
            new_name='creado_en',
        ),
        migrations.RenameField(
            model_name='metodopago',
            old_name='fecha_creacion',
            new_name='creado_en',
        ),
        migrations.RenameField(
            model_name='ticketsoporte',
            old_name='fecha_actualizacion',
            new_name='actualizado_en',
        ),
        migrations.RenameField(
            model_name='ticketsoporte',
            old_name='fecha_creacion',
            new_name='creado_en',
        ),
        migrations.RenameField(
            model_name='ticketsoporte',
            old_name='descripcion',
            new_name='mensaje',
        ),
        migrations.AlterUniqueTogether(
            name='resena',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='metodopago',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='ticketsoporte',
            name='categoria',
        ),
        migrations.AddField(
            model_name='mensajesoporte',
            name='es_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resena',
            name='aprobada',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resena',
            name='pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='sabores.pedido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketsoporte',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='sabores.pedido'),
        ),
        migrations.AddField(
            model_name='ticketsoporte',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=20),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='nombre_titular',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='numero_tarjeta',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='tipo',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resena',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketsoporte',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_soporte', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='resena',
            unique_together={('cliente', 'platillo', 'pedido')},
        ),
    ]
