# Generated by Django 5.2 on 2025-05-05 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0005_alter_mensajesoporte_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resena',
            unique_together={('cliente', 'pedido')},
        ),
        migrations.RemoveField(
            model_name='resena',
            name='platillo',
        ),
    ]
