# Generated by Django 5.2 on 2025-05-05 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0006_alter_resena_unique_together_remove_resena_platillo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_pagados', to='sabores.metodopago'),
        ),
    ]
