# Generated by Django 5.2 on 2025-05-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0008_rename_metodo_pago_pedido_tipo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo_pago',
            field=models.CharField(blank=True, choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=20, null=True),
        ),
    ]
