# Generated by Django 5.2 on 2025-05-04 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0002_pedido_detallepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pregunta_seguridad',
            field=models.CharField(blank=True, help_text='Pregunta de seguridad para recuperar contraseña', max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='respuesta_seguridad',
            field=models.CharField(blank=True, help_text='Respuesta a la pregunta de seguridad', max_length=200),
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tarjeta_credito', 'Tarjeta de Crédito'), ('tarjeta_debito', 'Tarjeta de Débito'), ('paypal', 'PayPal'), ('efectivo', 'Efectivo')], max_length=20)),
                ('nombre_titular', models.CharField(max_length=100)),
                ('numero_tarjeta', models.CharField(max_length=4)),
                ('fecha_expiracion', models.CharField(blank=True, max_length=5, null=True)),
                ('es_predeterminado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('pedido', 'Problema con Pedido'), ('pago', 'Problema de Pago'), ('cuenta', 'Cuenta'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MensajeSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='sabores.ticketsoporte')),
            ],
            options={
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('platillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='sabores.platillo')),
            ],
            options={
                'unique_together': {('platillo', 'cliente')},
            },
        ),
    ]
