# Generated by Django 5.2 on 2025-05-05 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0007_pedido_metodo_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='metodo_pago',
            new_name='tipo_pago',
        ),
    ]
